from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QPushButton
from PyQt6.QtGui import QFont

def price_extractor(string):
    price = string.split('-')[1].split('.')[1].strip()
    return int(price)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget {\n"
"    background-color: pink\n"
"}\n"
"\n"
"QLabel {\n"
"\n"
"    color : purple\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.item1 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item1.setFont(font)
        self.item1.setIconSize(QtCore.QSize(40, 40))
        self.item1.setObjectName("item1")
        self.verticalLayout.addWidget(self.item1)
        self.item2 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item2.setFont(font)
        self.item2.setIconSize(QtCore.QSize(40, 40))
        self.item2.setObjectName("item2")
        self.verticalLayout.addWidget(self.item2)
        self.item3 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item3.setFont(font)
        self.item3.setIconSize(QtCore.QSize(40, 40))
        self.item3.setObjectName("item3")
        self.verticalLayout.addWidget(self.item3)
        self.item4 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item4.setFont(font)
        self.item4.setIconSize(QtCore.QSize(40, 40))
        self.item4.setObjectName("item4")
        self.verticalLayout.addWidget(self.item4)
        self.item5 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item5.setFont(font)
        self.item5.setIconSize(QtCore.QSize(40, 40))
        self.item5.setObjectName("item5")
        self.verticalLayout.addWidget(self.item5)
        self.item6 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item6.setFont(font)
        self.item6.setIconSize(QtCore.QSize(40, 40))
        self.item6.setObjectName("item6")
        self.verticalLayout.addWidget(self.item6)
        self.item7 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item7.setFont(font)
        self.item7.setIconSize(QtCore.QSize(40, 40))
        self.item7.setObjectName("item7")
        self.verticalLayout.addWidget(self.item7)
        self.item8 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item8.setFont(font)
        self.item8.setIconSize(QtCore.QSize(40, 40))
        self.item8.setObjectName("item8")
        self.verticalLayout.addWidget(self.item8)
        self.item9 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item9.setFont(font)
        self.item9.setIconSize(QtCore.QSize(40, 40))
        self.item9.setObjectName("item9")
        self.verticalLayout.addWidget(self.item9)
        self.item10 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.item10.setFont(font)
        self.item10.setIconSize(QtCore.QSize(40, 40))
        self.item10.setObjectName("item10")
        self.verticalLayout.addWidget(self.item10)
        
        self.btn = QPushButton("Click to process Total Bill")
        self.btn.setFont(QFont("Consolas", 15))
        self.btn.clicked.connect(self.total_bill)
        self.verticalLayout.addWidget(self.btn)

        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_bill = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_bill.setFont(font)
        self.label_bill.setObjectName("label_bill")
        self.horizontalLayout.addWidget(self.label_bill)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.total_bill()


    def total_bill(self):
        price = 0
        items = [self.item1, self.item2, self.item3, self.item4, self.item5, self.item6, self.item7,
            self.item8, self.item9,self.item10]

        for item in items:
            if item.isChecked():
                txt = item.text()
                price += price_extractor(txt)
        self.label_bill.setNum(price)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Gugu\'s Kitchen"))
        self.label.setText(_translate("Form", "Gugu\'s Kitchen"))
        self.item1.setText(_translate("Form", "Roti - Rs. 10"))
        self.item2.setText(_translate("Form", "Aloo Paratha - Rs. 10"))
        self.item3.setText(_translate("Form", "Plain Paratha - Rs. 7"))
        self.item4.setText(_translate("Form", "Naan - Rs. 10"))
        self.item5.setText(_translate("Form", "Aloo Sabzi - Rs. 50"))
        self.item6.setText(_translate("Form", "Daal - Rs. 40"))
        self.item7.setText(_translate("Form", "Rajma - Rs. 50"))
        self.item8.setText(_translate("Form", "Chawal - Rs. 30"))
        self.item9.setText(_translate("Form", "Chai - Rs. 10"))
        self.item10.setText(_translate("Form", "Coffee - Rs. 10"))
        self.label_2.setText(_translate("Form", "Total Bill Amount:"))
        self.label_bill.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
